### ISSUE TITLE
undefined symbol: nvtxRangeEnd

### ISSUE THREAD

**Issue by wl1136** [NVIDIA/nvtx-plugins#1] opened 2019-07-19 05:54 UTC
After installing this nvtx-plugins successfully, i tried to run the example code "tf_sessoin_example.py", but there were errors existing as below:

$ python3 tf_session_example.py 
Traceback (most recent call last):
  File "tf_session_example.py", line 19, in <module>
    import nvtx.plugins.tf as nvtx_tf
  File "/home/david/Software/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/nvtx/plugins/tf/__init__.py", line 37, in <module>
    import nvtx.plugins.tf.ops
  File "/home/david/Software/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/nvtx/plugins/tf/ops.py", line 29, in <module>
    nvtx_tf_ops = load_library('lib/nvtx_ops' + get_ext_suffix())
  File "/home/david/Software/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/nvtx/plugins/tf/ext_utils.py", line 54, in load_library
    library = _load_library.load_op_library(filename)
  File "/home/david/Software/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
**tensorflow.python.framework.errors_impl.NotFoundError: /home/david/Software/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/nvtx/plugins/tf/lib/nvtx_ops.cpython-36m-x86_64-linux-gnu.so: undefined symbol: nvtxRangeEnd**

**Testing environment:
OS: ubuntu 16.04
CUDA: 10.0.130
conda env: (under anaconda 3.0) python3.6 + tensorflow_1.14-gpu version + gcc 4.8.5**

Would please help me to figure out the reason and give some suggestions on how to fix it ? 
Thanks

**Comment by DEKHTIARJonathan** [comment] 2019-07-20 15:14
Could you please provide a container to reproduce the error ? We couldn't managed to reproduce.

We recommend using our TensorFlow prebuilt container to avoid any dependency issue:

```bash
docker run -it --rm \
  --runtime=nvidia \
  --ipc='host' \
  -v $PWD:/workspace/nvtx \
  nvcr.io/nvidia/tensorflow:19.06-py3 /bin/bash
```

Or the official TF container (you will need to execute `apt update && apt install g++-4.8`):

```
docker run -it --rm \
  --runtime=nvidia \
  --ipc='host' \
  -v $PWD:/workspace/nvtx \
  tensorflow/tensorflow:latest-gpu-py3 /bin/bash
```

Just in case, we tried a fix: [nvtx-plugins-0.1.2.tar.gz](https://github.com/NVIDIA/nvtx-plugins/files/3413744/nvtx-plugins-0.1.2.tar.gz) (build from 023fff49bcaf9a41b33eaf12b18c1b9e46e13b3c)


Could you try: `pip install nvtx-plugins-0.1.2.tar.gz`

**Comment by DEKHTIARJonathan** [comment] 2019-08-05 11:49
Closing due to no answer. Please re-open if you still have the issue

**Closed as completed by DEKHTIARJonathan** 2019-08-05 11:49 UTC

**Comment by xyhuang** [comment] 2019-08-21 01:49
had the same issue but building from source worked for me.
I did not look into details, just posting here in case it could help.
(ubuntu 18.04 + cuda 10.0 + gcc 4.8.5 + python 3.6 + tf 1.13.2-gpu)
